version: '3.1'

services:

  db:
    container_name: mysql-8.3.0
    image: mysql:8.3.0
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Br@yeser123*
    ports:
      - 3308:3306

  adminer:
    container_name: adminer-4.8.0-standalone
    image: adminer
    restart: always
    ports:
      - 9080:8080
  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - 9081:80
      # Change the number before : to the port the SMTP server should be accessible on
      - 9025:25
